# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a62d4f695bc35c3bad8436ffb878f35284a0a3f6d139ef6b29ce4c93863df1c70a40fa304772dc1c022ece6a30ae2c4fee85279abde5787926ce81c648683a

test:
  secret_key_base: 3d5272a45181fa2241f99ca39a96fb3943a71bfe73f2af91db1311a8dd645e0c25ec387da81376c726c95229410a44e7dd7f63c37147c9614613fecb5d60a3ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
